apiVersion: v1
kind: ConfigMap
metadata:
  name: web-a-cfg
  namespace: web
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Web A</title>
    </head>
    <body>
        <h1>Welcome to web A!</h1>
    </body>
    </html>
# after change run "kubectl rollout restart deployment web -n web"
