apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-web-chart.fullname" . }}-content
  labels:
    {{- include "my-web-chart.labels" . | nindent 4 }}
{{- with .Values.contentData }}
data:
  {{- toYaml . | nindent 8 }}
{{- end }}
